name: Test Oysho page
on:
  schedule:
    - cron: '0/10 * * * *'

    
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Cypress and run tests
        uses: cypress-io/github-action@v6
        with:
          start: npm run cypress:open
